/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __XDP_BPF_SKEL_H__
#define __XDP_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

#define BPF_SKEL_SUPPORTS_MAP_AUTO_ATTACH 1

struct xdp_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_program *drop_packets;
	} progs;
	struct {
		struct bpf_link *drop_packets;
	} links;

#ifdef __cplusplus
	static inline struct xdp_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct xdp_bpf *open_and_load();
	static inline int load(struct xdp_bpf *skel);
	static inline int attach(struct xdp_bpf *skel);
	static inline void detach(struct xdp_bpf *skel);
	static inline void destroy(struct xdp_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
xdp_bpf__destroy(struct xdp_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
xdp_bpf__create_skeleton(struct xdp_bpf *obj);

static inline struct xdp_bpf *
xdp_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct xdp_bpf *obj;
	int err;

	obj = (struct xdp_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = xdp_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	xdp_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct xdp_bpf *
xdp_bpf__open(void)
{
	return xdp_bpf__open_opts(NULL);
}

static inline int
xdp_bpf__load(struct xdp_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct xdp_bpf *
xdp_bpf__open_and_load(void)
{
	struct xdp_bpf *obj;
	int err;

	obj = xdp_bpf__open();
	if (!obj)
		return NULL;
	err = xdp_bpf__load(obj);
	if (err) {
		xdp_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
xdp_bpf__attach(struct xdp_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
xdp_bpf__detach(struct xdp_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *xdp_bpf__elf_bytes(size_t *sz);

static inline int
xdp_bpf__create_skeleton(struct xdp_bpf *obj)
{
	struct bpf_object_skeleton *s;
	struct bpf_map_skeleton *map __attribute__((unused));
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "xdp_bpf";
	s->obj = &obj->obj;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "drop_packets";
	s->progs[0].prog = &obj->progs.drop_packets;
	s->progs[0].link = &obj->links.drop_packets;

	s->data = xdp_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *xdp_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x90\x0b\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x18\0\
\x01\0\xb7\0\0\0\x01\0\0\0\x95\0\0\0\0\0\0\0\x47\x50\x4c\0\x01\x11\x01\x25\x25\
\x13\x05\x03\x25\x72\x17\x10\x17\x1b\x25\x11\x1b\x12\x06\x73\x17\0\0\x02\x34\0\
\x03\x25\x49\x13\x3f\x19\x3a\x0b\x3b\x0b\x02\x18\0\0\x03\x01\x01\x49\x13\0\0\
\x04\x21\0\x49\x13\x37\x0b\0\0\x05\x24\0\x03\x25\x3e\x0b\x0b\x0b\0\0\x06\x24\0\
\x03\x25\x0b\x0b\x3e\x0b\0\0\x07\x04\x01\x49\x13\x03\x25\x0b\x0b\x3a\x0b\x3b\
\x05\0\0\x08\x28\0\x03\x25\x1c\x0f\0\0\x09\x2e\x01\x11\x1b\x12\x06\x40\x18\x7a\
\x19\x03\x25\x3a\x0b\x3b\x0b\x27\x19\x49\x13\x3f\x19\0\0\x0a\x05\0\x03\x25\x3a\
\x0b\x3b\x0b\x49\x13\0\0\x0b\x0f\0\x49\x13\0\0\x0c\x13\x01\x03\x25\x0b\x0b\x3a\
\x0b\x3b\x05\0\0\x0d\x0d\0\x03\x25\x49\x13\x3a\x0b\x3b\x05\x38\x0b\0\0\x0e\x16\
\0\x49\x13\x03\x25\x3a\x0b\x3b\x05\0\0\0\xca\0\0\0\x05\0\x01\x08\0\0\0\0\x01\0\
\x1d\0\x01\x08\0\0\0\0\0\0\0\x02\x01\x10\0\0\0\x08\0\0\0\x02\x03\x2e\0\0\0\0\
\x08\x02\xa1\0\x03\x3a\0\0\0\x04\x3e\0\0\0\x04\0\x05\x04\x06\x01\x06\x05\x08\
\x07\x07\x5c\0\0\0\x0c\x04\x01\xe6\x78\x08\x07\0\x08\x08\x01\x08\x09\x02\x08\
\x0a\x03\x08\x0b\x04\0\x05\x06\x07\x04\x09\x01\x10\0\0\0\x01\x5a\x0d\0\x0b\x78\
\0\0\0\x0a\x0f\0\x0b\x7c\0\0\0\0\x05\x0e\x05\x04\x0b\x81\0\0\0\x0c\x17\x18\x01\
\x9f\xba\x0d\x10\xc4\0\0\0\x01\xa0\xba\0\x0d\x12\xc4\0\0\0\x01\xa1\xba\x04\x0d\
\x13\xc4\0\0\0\x01\xa2\xba\x08\x0d\x14\xc4\0\0\0\x01\xa3\xba\x0c\x0d\x15\xc4\0\
\0\0\x01\xa4\xba\x10\x0d\x16\xc4\0\0\0\x01\xa5\xba\x14\0\x0e\x5c\0\0\0\x11\x01\
\x8f\x7c\0\x64\0\0\0\x05\0\0\0\0\0\0\0\x27\0\0\0\x31\0\0\0\x69\0\0\0\x71\0\0\0\
\x76\0\0\0\x8a\0\0\0\x97\0\0\0\xa3\0\0\0\xac\0\0\0\xb5\0\0\0\xbc\0\0\0\xc9\0\0\
\0\xd4\0\0\0\xe1\0\0\0\xe5\0\0\0\xe9\0\0\0\xee\0\0\0\xf4\0\0\0\xfd\0\0\0\x07\
\x01\0\0\x17\x01\0\0\x26\x01\0\0\x35\x01\0\0\x55\x62\x75\x6e\x74\x75\x20\x63\
\x6c\x61\x6e\x67\x20\x76\x65\x72\x73\x69\x6f\x6e\x20\x31\x38\x2e\x31\x2e\x33\
\x20\x28\x31\x75\x62\x75\x6e\x74\x75\x31\x29\0\x78\x64\x70\x2e\x62\x70\x66\x2e\
\x63\0\x2f\x68\x6f\x6d\x65\x2f\x61\x73\x77\x69\x6e\x6e\x61\x74\x68\x2f\x64\x5f\
\x64\x72\x69\x76\x65\x2f\x43\x6f\x64\x69\x6e\x67\x2f\x7a\x6f\x68\x6f\x5f\x69\
\x6e\x63\x75\x62\x61\x74\x69\x6f\x6e\x2f\x65\x62\x70\x66\x2f\x78\x64\x70\0\x4c\
\x49\x43\x45\x4e\x53\x45\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\
\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x75\x6e\x73\x69\x67\x6e\x65\x64\
\x20\x69\x6e\x74\0\x58\x44\x50\x5f\x41\x42\x4f\x52\x54\x45\x44\0\x58\x44\x50\
\x5f\x44\x52\x4f\x50\0\x58\x44\x50\x5f\x50\x41\x53\x53\0\x58\x44\x50\x5f\x54\
\x58\0\x58\x44\x50\x5f\x52\x45\x44\x49\x52\x45\x43\x54\0\x78\x64\x70\x5f\x61\
\x63\x74\x69\x6f\x6e\0\x64\x72\x6f\x70\x5f\x70\x61\x63\x6b\x65\x74\x73\0\x69\
\x6e\x74\0\x63\x74\x78\0\x64\x61\x74\x61\0\x5f\x5f\x75\x33\x32\0\x64\x61\x74\
\x61\x5f\x65\x6e\x64\0\x64\x61\x74\x61\x5f\x6d\x65\x74\x61\0\x69\x6e\x67\x72\
\x65\x73\x73\x5f\x69\x66\x69\x6e\x64\x65\x78\0\x72\x78\x5f\x71\x75\x65\x75\x65\
\x5f\x69\x6e\x64\x65\x78\0\x65\x67\x72\x65\x73\x73\x5f\x69\x66\x69\x6e\x64\x65\
\x78\0\x78\x64\x70\x5f\x6d\x64\0\x14\0\0\0\x05\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x0c\x01\0\0\x0c\x01\0\0\xfa\0\0\0\0\
\0\0\0\0\0\0\x02\x02\0\0\0\x01\0\0\0\x06\0\0\x04\x18\0\0\0\x08\0\0\0\x03\0\0\0\
\0\0\0\0\x0d\0\0\0\x03\0\0\0\x20\0\0\0\x16\0\0\0\x03\0\0\0\x40\0\0\0\x20\0\0\0\
\x03\0\0\0\x60\0\0\0\x30\0\0\0\x03\0\0\0\x80\0\0\0\x3f\0\0\0\x03\0\0\0\xa0\0\0\
\0\x4e\0\0\0\0\0\0\x08\x04\0\0\0\x54\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\
\0\x01\0\0\x0d\x06\0\0\0\x61\0\0\0\x01\0\0\0\x65\0\0\0\0\0\0\x01\x04\0\0\0\x20\
\0\0\x01\x69\0\0\0\x01\0\0\x0c\x05\0\0\0\xd1\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\
\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x08\0\0\0\x0a\0\0\0\x04\0\0\0\xd6\0\0\0\0\0\0\
\x01\x04\0\0\0\x20\0\0\0\xea\0\0\0\0\0\0\x0e\x09\0\0\0\x01\0\0\0\xf2\0\0\0\x01\
\0\0\x0f\0\0\0\0\x0b\0\0\0\0\0\0\0\x04\0\0\0\0\x78\x64\x70\x5f\x6d\x64\0\x64\
\x61\x74\x61\0\x64\x61\x74\x61\x5f\x65\x6e\x64\0\x64\x61\x74\x61\x5f\x6d\x65\
\x74\x61\0\x69\x6e\x67\x72\x65\x73\x73\x5f\x69\x66\x69\x6e\x64\x65\x78\0\x72\
\x78\x5f\x71\x75\x65\x75\x65\x5f\x69\x6e\x64\x65\x78\0\x65\x67\x72\x65\x73\x73\
\x5f\x69\x66\x69\x6e\x64\x65\x78\0\x5f\x5f\x75\x33\x32\0\x75\x6e\x73\x69\x67\
\x6e\x65\x64\x20\x69\x6e\x74\0\x63\x74\x78\0\x69\x6e\x74\0\x64\x72\x6f\x70\x5f\
\x70\x61\x63\x6b\x65\x74\x73\0\x78\x64\x70\0\x2f\x68\x6f\x6d\x65\x2f\x61\x73\
\x77\x69\x6e\x6e\x61\x74\x68\x2f\x64\x5f\x64\x72\x69\x76\x65\x2f\x43\x6f\x64\
\x69\x6e\x67\x2f\x7a\x6f\x68\x6f\x5f\x69\x6e\x63\x75\x62\x61\x74\x69\x6f\x6e\
\x2f\x65\x62\x70\x66\x2f\x78\x64\x70\x2f\x78\x64\x70\x2e\x62\x70\x66\x2e\x63\0\
\x20\x20\x20\x20\x72\x65\x74\x75\x72\x6e\x20\x58\x44\x50\x5f\x44\x52\x4f\x50\
\x3b\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\
\x54\x59\x50\x45\x5f\x5f\0\x4c\x49\x43\x45\x4e\x53\x45\0\x6c\x69\x63\x65\x6e\
\x73\x65\0\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\x1c\0\0\0\
\x30\0\0\0\0\0\0\0\x08\0\0\0\x76\0\0\0\x01\0\0\0\0\0\0\0\x07\0\0\0\x10\0\0\0\
\x76\0\0\0\x01\0\0\0\0\0\0\0\x7a\0\0\0\xbc\0\0\0\x05\x4c\0\0\0\0\0\0\x0c\0\0\0\
\xff\xff\xff\xff\x04\0\x08\0\x08\x7c\x0b\0\x14\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x10\0\0\0\0\0\0\0\x70\0\0\0\x05\0\x08\0\x50\0\0\0\x08\x01\x01\xfb\x0e\x0d\0\
\x01\x01\x01\x01\0\0\0\x01\0\0\x01\x01\x01\x1f\x02\0\0\0\0\x38\0\0\0\x03\x01\
\x1f\x02\x0f\x05\x1e\x02\x3a\0\0\0\0\x97\x89\x8a\x54\x36\x62\xe5\x3f\x0b\x6e\
\x0f\xbc\x1b\xc4\x6a\x50\x44\0\0\0\x01\x49\xe8\xf6\xb7\xb7\x85\xe9\xfe\x93\x55\
\x30\xfa\x73\x2c\xaa\x01\x04\0\x05\x05\x0a\0\x09\x02\0\0\0\0\0\0\0\0\x03\x12\
\x01\x02\x02\0\x01\x01\x2f\x68\x6f\x6d\x65\x2f\x61\x73\x77\x69\x6e\x6e\x61\x74\
\x68\x2f\x64\x5f\x64\x72\x69\x76\x65\x2f\x43\x6f\x64\x69\x6e\x67\x2f\x7a\x6f\
\x68\x6f\x5f\x69\x6e\x63\x75\x62\x61\x74\x69\x6f\x6e\x2f\x65\x62\x70\x66\x2f\
\x78\x64\x70\0\x2e\0\x78\x64\x70\x2e\x62\x70\x66\x2e\x63\0\x76\x6d\x6c\x69\x6e\
\x75\x78\x2e\x68\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\xbc\0\0\0\x04\0\xf1\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x03\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x0a\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x0b\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x03\0\x11\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x13\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x15\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x39\0\0\0\x12\0\x03\0\0\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\xdf\0\0\0\x11\0\
\x04\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\x03\0\0\0\x03\0\0\0\
\x11\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x15\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\
\x1f\0\0\0\0\0\0\0\x03\0\0\0\x06\0\0\0\x08\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x0c\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x10\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x14\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x18\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x1c\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x20\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x24\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x28\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x2c\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x30\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x34\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x38\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x3c\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x40\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x44\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x48\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x4c\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x50\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x54\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x58\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x5c\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x60\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x64\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x08\0\0\0\0\0\0\0\x02\0\0\0\x0b\0\0\0\
\x10\0\0\0\0\0\0\0\x02\0\0\0\x02\0\0\0\x1c\x01\0\0\0\0\0\0\x04\0\0\0\x0b\0\0\0\
\x2c\0\0\0\0\0\0\0\x04\0\0\0\x02\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\0\x02\0\0\0\
\x14\0\0\0\0\0\0\0\x03\0\0\0\x07\0\0\0\x18\0\0\0\0\0\0\0\x02\0\0\0\x02\0\0\0\
\x22\0\0\0\0\0\0\0\x03\0\0\0\x09\0\0\0\x26\0\0\0\0\0\0\0\x03\0\0\0\x09\0\0\0\
\x32\0\0\0\0\0\0\0\x03\0\0\0\x09\0\0\0\x47\0\0\0\0\0\0\0\x03\0\0\0\x09\0\0\0\
\x64\0\0\0\0\0\0\0\x02\0\0\0\x02\0\0\0\x0a\x0b\0\x2e\x64\x65\x62\x75\x67\x5f\
\x61\x62\x62\x72\x65\x76\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x42\x54\
\x46\x2e\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x73\x74\x72\
\x5f\x6f\x66\x66\x73\x65\x74\x73\0\x64\x72\x6f\x70\x5f\x70\x61\x63\x6b\x65\x74\
\x73\0\x2e\x64\x65\x62\x75\x67\x5f\x73\x74\x72\0\x2e\x64\x65\x62\x75\x67\x5f\
\x6c\x69\x6e\x65\x5f\x73\x74\x72\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\
\x61\x64\x64\x72\0\x78\x64\x70\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\
\x69\x6e\x66\x6f\0\x2e\x6c\x6c\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x6c\
\x69\x63\x65\x6e\x73\x65\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x6c\x69\
\x6e\x65\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x66\x72\x61\x6d\x65\0\
\x78\x64\x70\x2e\x62\x70\x66\x2e\x63\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\
\x79\x6d\x74\x61\x62\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\x4c\x49\x43\x45\x4e\
\x53\x45\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc6\
\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa2\x0a\0\0\0\0\0\0\xe7\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x0f\0\0\0\x01\0\0\0\
\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x71\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x93\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x50\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x01\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x54\0\0\0\0\0\0\0\
\xbd\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x79\0\0\0\
\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x11\x01\0\0\0\0\0\0\xce\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x75\0\0\0\x09\0\0\0\x40\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x20\x08\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x17\0\0\0\
\x06\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x26\0\0\0\x01\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\xdf\x01\0\0\0\0\0\0\x68\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x22\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x60\x08\0\0\0\0\0\0\x80\x01\0\0\0\0\0\0\x17\0\0\0\x08\0\0\0\x08\0\0\0\0\
\0\0\0\x10\0\0\0\0\0\0\0\x46\0\0\0\x01\0\0\0\x30\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x47\x02\0\0\0\0\0\0\x3c\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x01\
\0\0\0\0\0\0\0\x65\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x83\x03\0\0\
\0\0\0\0\x18\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x61\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xe0\x09\0\0\0\0\0\0\x20\
\0\0\0\0\0\0\0\x17\0\0\0\x0b\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\xda\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9c\x03\0\0\0\0\0\0\x1e\x02\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd6\0\0\0\x09\0\0\0\
\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x0a\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x17\0\0\
\0\x0d\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x19\0\0\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xbc\x05\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x15\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x10\x0a\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x17\0\0\0\x0f\0\0\0\x08\0\0\0\
\0\0\0\0\x10\0\0\0\0\0\0\0\xaf\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x10\x06\0\0\0\0\0\0\x28\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\xab\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x30\x0a\0\0\0\
\0\0\0\x20\0\0\0\0\0\0\0\x17\0\0\0\x11\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\
\0\x9f\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x38\x06\0\0\0\0\0\0\x74\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9b\0\0\0\x09\
\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x50\x0a\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\
\x17\0\0\0\x13\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x51\0\0\0\x01\0\0\0\
\x30\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xac\x06\0\0\0\0\0\0\x4e\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x85\0\0\0\x03\x4c\xff\x6f\0\0\0\
\x80\0\0\0\0\0\0\0\0\0\0\0\0\xa0\x0a\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\x17\0\0\0\0\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xce\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x07\0\0\0\0\0\0\x20\x01\0\0\0\0\0\0\x01\0\0\0\x0a\0\0\0\x08\0\
\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct xdp_bpf *xdp_bpf::open(const struct bpf_object_open_opts *opts) { return xdp_bpf__open_opts(opts); }
struct xdp_bpf *xdp_bpf::open_and_load() { return xdp_bpf__open_and_load(); }
int xdp_bpf::load(struct xdp_bpf *skel) { return xdp_bpf__load(skel); }
int xdp_bpf::attach(struct xdp_bpf *skel) { return xdp_bpf__attach(skel); }
void xdp_bpf::detach(struct xdp_bpf *skel) { xdp_bpf__detach(skel); }
void xdp_bpf::destroy(struct xdp_bpf *skel) { xdp_bpf__destroy(skel); }
const void *xdp_bpf::elf_bytes(size_t *sz) { return xdp_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
xdp_bpf__assert(struct xdp_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __XDP_BPF_SKEL_H__ */
